In [1]:
from tensorflow.keras.datasets import fashion_mnist
import numpy as np
import matplotlib.pyplot as plt
from tqdm.auto import tqdm
import seaborn as sns
import pandas as pd

C:\Users\Mohsen\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [16]:
class MaxNet:
    def __init__(self, epsilon=0.15):
        self.epsilon = epsilon
    
    def f(self, x):
        return max(0, x)
    
    def max(self, x):
        a = np.array(x)
        print(a)
        while (a > 0).sum() > 1:
            a_old = a.copy()
            for i in range(len(a)):
                a[i] = self.f(a_old[i] - self.epsilon * np.sum(np.delete(a_old, i)))
            print(a)
        return np.argmax(a), x[np.argmax(a)]
        
maxnet = MaxNet(epsilon=0.15)
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
maxnet.max(x=[1.2, 1.1, 1, 0.9, 0.95, 1.15])

[ 1.200  1.100  1.000  0.900  0.950  1.150]
[ 0.435  0.320  0.205  0.090  0.148  0.377]
[ 0.264  0.132  0.000  0.000  0.000  0.198]
[ 0.215  0.062  0.000  0.000  0.000  0.139]
[ 0.184  0.010  0.000  0.000  0.000  0.097]
[ 0.168  0.000  0.000  0.000  0.000  0.068]
[ 0.158  0.000  0.000  0.000  0.000  0.043]
[ 0.152  0.000  0.000  0.000  0.000  0.019]
[ 0.149  0.000  0.000  0.000  0.000  0.000]


(0, 1.2)